export const patientData = [
  { Gender: ["Male", "Female"] },
  { Ethnicity: ["Caucasian", "AfricanAmerican", "Hispanic", "Asian", "Other"] },
  { Heart_Diseases: ["No", "Mild", "Moderate", "Severe"] },
  { Hypertension: ["No", "Controlled", "Uncontrolled"] },
  { Diabetes: ["No", "Controlled", "Uncontrolled"] },
  { COPD: ["No", "Mild", "Moderate", "Severe"] },
  { CKD: ["No", "Stage 1-2", "Stage 3-4", "Stage 5"] },
  { Cancer: ["No", "Stage 0", "Stage 1", "Stage 2", "Stage 3", "Stage 4"] },
  { HIV_AIDS: ["No", "Yes"] },
  { IBD: ["No", "Yes"] },
  { Osteoarthritis: ["No", "Mild", "Moderate", "Severe"] },
  { Neurological_Disorders: ["No", "Mild", "Moderate", "Severe"] },
  { Liver_Related_Conditions: ["Good", "Bad"] },
  { Other: ["No", "Mild", "Moderate", "Severe"] },
  { Hemoglobin_Levels: ["Normal", "Low", "Significantly Low"] },
  { Creatinine_Levels: ["Normal", "Elevated", "Significantly Elevated"] },
  { Blood_Glucose_Levels: ["Normal", "Elevated", "Significantly Elevated"] },
  { Cholesterol_Levels: ["Normal", "Elevated", "Significantly Elevated"] },
  { Inflammatory_Markers: ["Normal", "Elevated", "Significantly Elevated"] },
  { Liver_Function_Tests: ["Normal", "Abnormal"] },
  { Renal_Function_Tests: ["Normal", "Abnormal"] },
  { Depression: ["No", "Mild", "Moderate", "Severe"] },
  { Anxiety: ["No", "Occasional", "Frequent"] },
  { Alcohol: ["No", "Occasional", "Frequent"] },
  { Drugs: ["No", "Occasional", "Frequent"] },
  { Smoking: ["No", "Mild", "Moderate", "Severe"] },
  { Number_Of_Medications: ["0-3", "4-6", "7 or more"] },
  { Medication_Adherence: ["Fully", "Partially", "No"] },
  { Medication_Type: ["Low-risk", "Moderate-risk", "High-risk"] },
  { Side_Effects_And_Complications: ["No", "Mild", "Severe"] },
  { Discharge_To: ["Home", "Nursing Facility", "Rehabilitation", "Death"] },
  { Follow_Up_Scheduled: [0, 1] },
  {
    Follow_Up_Attendance: [
      "Always attends",
      "Misses occasionally",
      "Frequently misses",
    ],
  },
  { Health_Literacy: ["High", "Moderate", "Low"] },
  { Proactivity_In_Health: ["Proactive", "Moderate", "Passive"] },
  { Income_Level: ["High", "Middle", "Low"] },
  { Employment_Status: ["Full-time", "Part-time", "Unemployed"] },
  { Education_Level: ["College", "High school", "Less than high school"] },
  { Insurance_Coverage: ["Full", "Partial", "None"] },
  { Access_To_Healthy_Food: ["Easy", "Moderate", "Limited"] },
  { Insurance_Type: ["Public", "Private", "Uninsured"] },
  {
    Household_Composition: [
      "Lives alone",
      "Lives with friends/roommates",
      "Lives with family",
    ],
  },
  { Housing_Stability: ["Stable", "Temporary housing", "Homeless"] },
  { Neighborhood_Safety: ["Moderate risk", "High crime area", "Safe area"] },
  { Support_System_Availability: ["Strong", "Moderate", "Weak"] },
];

export const patientData_for_input = [
  "Previous_Readmissions",
  "Emergency_Visits",
  "Hospital_Stay_Duration",
  "Distance_From_Hospital",
];
